version: '3.0'

services:
  db:
    image: postgres:13.2
    restart: always
    ports:
      - 54320:5432
    env_file:
      - ./env/db.env
  api:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    ports:  
      - '8080:5000'
    env_file:
      - ./env/api.env
    depends_on:
      - db
    
